package grafnus.portalshard.engine.events;

public enum EEvents {
    PLAYER_INTERACT_RESPAWN_ANCHOR,
    PLAYER_PORTAL,
    CRYING_OBSIDIAN_BREAK,
    RESPAWN_ANCHOR_BREAK,
    BLOCK_BELOW_PORTAL_PHYSICS,
    BLOCK_ABOVE_PORTAL_PHYSICS,
}
